// Tơ Hồng — icon helper. Maps the prototype's kebab-case Lucide names to
// lucide-react components so ported screens read just like the design files
// (was `BIcon` rendering `window.lucide`). Props mirror BIcon: name, size,
// color (→ stroke), sw (→ strokeWidth).
import {
  Menu,
  Bell,
  BellRing,
  CalendarHeart,
  CalendarClock,
  Calendar,
  Wallet,
  Users,
  UserPlus,
  UserRound,
  ListChecks,
  List,
  Store,
  ArrowUp,
  ArrowUpRight,
  ArrowRight,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Check,
  CheckCircle2,
  Sparkles,
  WandSparkles,
  Clock4,
  Clock,
  X,
  Search,
  Plus,
  Camera,
  UtensilsCrossed,
  Flower2,
  Gem,
  Shirt,
  Shield,
  ShieldCheck,
  Pencil,
  Trash2,
  CircleSmall,
  Gift,
  ScrollText,
  MessageCircle,
  House,
  AlertCircle,
  Info,
  Lock,
  Star,
  Share2,
  Pointer,
  MessagesSquare,
  HeartHandshake,
  Lightbulb,
  RefreshCw,
  RotateCcw,
  ReceiptText,
  CornerDownRight,
  Heart,
  Building2,
  SearchX,
  SlidersHorizontal,
  ClipboardList,
  CircleDashed,
  Music2,
  MapPin,
  Palette,
  Bookmark,
} from 'lucide-react';

const MAP = {
  menu: Menu,
  bell: Bell,
  'bell-ring': BellRing,
  'calendar-heart': CalendarHeart,
  'calendar-clock': CalendarClock,
  calendar: Calendar,
  wallet: Wallet,
  users: Users,
  'user-plus': UserPlus,
  'user-round': UserRound,
  'list-checks': ListChecks,
  list: List,
  store: Store,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'arrow-right': ArrowRight,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  check: Check,
  'check-circle-2': CheckCircle2,
  sparkles: Sparkles,
  'wand-sparkles': WandSparkles,
  'clock-4': Clock4,
  clock: Clock,
  x: X,
  search: Search,
  plus: Plus,
  camera: Camera,
  'utensils-crossed': UtensilsCrossed,
  flower: Flower2,
  'flower-2': Flower2,
  gem: Gem,
  shirt: Shirt,
  shield: Shield,
  'shield-check': ShieldCheck,
  pencil: Pencil,
  'trash-2': Trash2,
  'circle-small': CircleSmall,
  gift: Gift,
  'scroll-text': ScrollText,
  'message-circle': MessageCircle,
  house: House,
  'alert-circle': AlertCircle,
  info: Info,
  lock: Lock,
  star: Star,
  'share-2': Share2,
  'hand-pointer': Pointer,
  'messages-square': MessagesSquare,
  'heart-handshake': HeartHandshake,
  lightbulb: Lightbulb,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'receipt-text': ReceiptText,
  'corner-down-right': CornerDownRight,
  heart: Heart,
  'building-2': Building2,
  'search-x': SearchX,
  'sliders-horizontal': SlidersHorizontal,
  'clipboard-list': ClipboardList,
  'circle-dashed': CircleDashed,
  'music-2': Music2,
  'map-pin': MapPin,
  palette: Palette,
  bookmark: Bookmark,
};

export function Icon({ name, size = 20, color = 'currentColor', sw = 1.85, ...rest }) {
  const Cmp = MAP[name];
  if (!Cmp) {
    if (import.meta.env?.DEV) console.warn(`Icon: unknown name "${name}"`);
    return null;
  }
  return <Cmp size={size} color={color} strokeWidth={sw} {...rest} />;
}

export default Icon;
